version:           '2'
services:
  #
  # BASE ENVIRONMENT
  #
  # Define the smallest building blocks to handle intercommunication with
  # every component with a shell environment and provide a volume layout For
  # project development
  #
  # For the developer, once you have a configuration setup the way you want, you
  # should stash this file unless told changes are being made.
  #
  app_environment:
    image:         symball/docker-images:base_php7
    stdin_open:    true
    tty:           true
    #
    # INTERNAL NETWORKING
    #
    links:
       - database_sql
       - database_couch
       - message_rabbitmq
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Log location
      - ./log/app_specific:/srv/app/logs
      - ./log/app_environment:/var/log
      # Project files
      - ./site:/srv


  #
  # DAEMON ENVIRONMENT
  #
  # A version of the base image running in an automated fashion. Inherits volumes
  # from the base environment
  #
  app_platform:
    image:         symball/docker-images:platform_php7
    volumes_from:
      - app_environment
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      - ./log/app_platform:/var/log/php7
  #
  # INGRESS CONTROLLER
  #
  # A gateway container for providing a single point of communication with
  # external services. For any See the docker/nginx/config_library path for
  # possible configs that should be dropped in to either the developer_config
  # or production_config folders.
  #
  external_gateway:
    image:         nginx:mainline-alpine
    links:
      - app_platform
      - database_couch
      - database_sql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prod_config/http:/etc/nginx/conf.d
      - ./nginx/prod_config/stream:/etc/nginx/conf.e
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/external_gateway:/var/log/nginx
    volumes_from:
      - app_platform
  #
  # INTERNAL SERVICES
  #
  # relational database
  database_sql:
    image:         mariadb:10
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/database_mysql:/var/log
    # TODO substitute with key service
    environment:
      - MYSQL_ROOT_PASSWORD=docker_stack
      - MYSQL_ROOT_HOST=%

  # document database
  database_couch:
     image:        couchdb
     volumes:
       - ./data/couch:/usr/local/var/lib/couchdb
       - ./log/database_couch:/var/log/couchdb
     # TODO substitute with key service
     environment:
      - COUCHDB_USER=docker_stack
      - COUCHDB_PASSWORD=docker_stack

  message_rabbitmq:
     image: rabbitmq:3-alpine
