version:           '2'
services:

  app_environment:
    container_name: dockerquickstack_environment_php7_mongo_developer
    stdin_open:    true
    tty:           true
    env_file: .env
    build:
      context: ./environment_php7_mongo_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_mongo
      # - database_sql
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Log location
      - ./log/app_specific:/srv/app/logs
      - ./log/app_environment:/var/log
      # Extra platform Configuration
      - ./environment_php7_mongo_developer/php.ini:/etc/php7/conf.d/overrides.ini
      # Project files
      - ../site:/srv

  app_platform:
    container_name: dockerquickstack_platform_php7_mongo_developer
    env_file: .env
    build:
      context: ./platform_php7_mongo_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes_from:
      - app_environment
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_mongo
      # - database_sql
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      - ./platform_php7_mongo_developer/php-fpm.conf:/etc/php7/php-fpm.conf
      - ./platform_php7_mongo_developer/pool_config.conf:/etc/php7/php-fpm.d/www.conf
      - ./log/app_platform:/var/log/php7

  external_gateway:
    container_name: dockerquickstack_external_gateway_developer
    env_file: .env
    build:
      context: ./nginx
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports:
      - 8080:8080
    links:
      - app_platform
      - database_mongo
    volumes:
      - ./nginx/dev_config/http:/etc/nginx/conf.d
      - ./nginx/dev_config/stream:/etc/nginx/conf.e
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/external_gateway:/var/log/nginx
    volumes_from:
      - app_platform

  #
  # INTERNAL SERVICES
  #
  # document database
  database_mongo:
    image:         mongo:3
    volumes:
      - ./data/mongo:/data/db
      - ./log/database_mongo:/var/log

  # relational database
  # database_sql:
  #    image:         mariadb:10
  #    volumes:
  #      - ./data/mysql:/var/lib/mysql
  #      - ./log/database_mysql:/var/log
  #    # TODO substitute with key service
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=docker_stack
  #      - MYSQL_USER=docker_stack
  #      - MYSQL_PASSWORD=docker_stack
  #      - MYSQL_DATABASE=docker_stack
  #      - MYSQL_ROOT_HOST=%

  # Fake SMTP service
  mail_server:
    image: mailhog/mailhog
    ports:
      - 8081:8025
