version:           '2'
services:

  app_environment:
    image: symball/pivot88-docker:base_php55_developer
    stdin_open:    true
    tty:           true
    env_file: .env
    build:
      context: ./base_php55_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Log location
      - ./log/symfony:/srv/app/logs
      - ./log/base:/var/log
      # Extra platform Configuration
      - ./base_php55_developer/php.ini:/etc/php5/cli/conf.d/overrides.ini
      # Project files
      - ~/pivot88/Pivot88WebPlatform:/srv
      - ~/pivot88/DataBundle:/srv/DataBundle
      - ~/.ssh:/home/php/.ssh

  app_platform:
    image: symball/pivot88-docker:platform_php55
    env_file: .env
    build:
      context: ./platform_php55_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes_from:
      - app_environment
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Extra platform Configuration
      - ./platform_php55_developer/pool_config.conf:/etc/php5/fpm/pool.d/www.conf
      - ./log/platform:/var/log/php5

  external_gateway:
    image:         nginx:mainline-alpine
    links:
      - app_platform
      - database_couch
      - database_sql
    ports:
      - 8080:80
      - 4430:443
    volumes:
      - ./nginx/dev_config/http:/etc/nginx/conf.d
      - ./nginx/dev_config/stream:/etc/nginx/conf.e
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    volumes_from:
      - app_platform

  database_sql:
    image:         mysql/mysql-server:5.5
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log
    ports:
      - 3306:3306
    # TODO Move in to a management system
    environment:
      - MYSQL_ROOT_PASSWORD=docker_stack
      - MYSQL_ROOT_HOST=%

  # Fake SMTP service
  mail_server:
    image: mailhog/mailhog
    ports:
      - 82:8025

  #
  # JENKINS AUTOMATION
  #
  jenkins:
    image: symball/jenkins-with-docker
    env_file: .env
    build:
      context: ./jenkins
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  # Log grabber
  # log_elk:
  #    image: sebp/elk:550
  #    ports:
  #     - 81:80
  #    volumes:
  #     - ./elk/logstash:/etc/logstash
  #     - ./elk/logstash/patterns:/opt/logstash/patterns
  #     - ./log:/internal_logs
