version:           '2'
services:

  app_environment:
    image: base:php55_developer
    stdin_open:    true
    tty:           true
    env_file: .env
    build:
      context: ./base_php55_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Log location
      - ./log/base_symfony_php7:/srv/app/logs
      # Extra platform Configuration
      - ./base_php7/php.ini:/etc/php7/conf.d/overrides.ini
      # Project files
      - ~/Development/pivot88/Pivot88WebPlatform:/srv
      - ~/Development/DataBundle:/srv/DataBundle
      - ~/.ssh:/home/php/.ssh

  app_platform:
    image:         platform:php55
    env_file: .env
    build:
      context: ./platform_php55
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes_from:
      - app_environment
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Extra platform Configuration
      - ./platform_php7/pool_config.conf:/etc/php7/php-fpm.d/www.conf
      - ./log/platform_php7:/var/log/php7

  external_gateway:
    image:         nginx:mainline-alpine
    links:
      - app_platform
      - database_couch
      - database_sql
    ports:
      - 8080:80
      - 4430:443
    volumes:
      - ./nginx/dev_config/http:/etc/nginx/conf.d
      - ./nginx/dev_config/stream:/etc/nginx/conf.e
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    volumes_from:
      - app_platform

  database_sql:
    image:         mysql/mysql-server:5.5
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log
    ports:
      - 3306:3306
    # TODO Move in to a management system
    environment:
      - MYSQL_ROOT_PASSWORD=docker_stack
      - MYSQL_ROOT_HOST=%

  # Fake SMTP service
  mail_server:
    image: mailhog/mailhog
    ports:
      - 82:8025

  # Log grabber
  # log_elk:
  #    image: sebp/elk:550
  #    ports:
  #     - 81:80
  #    volumes:
  #     - ./elk/logstash:/etc/logstash
  #     - ./elk/logstash/patterns:/opt/logstash/patterns
  #     - ./log:/internal_logs
