version:           '2'
services:

  app_environment:
    image: symball/pivot88-docker:base_php7_developer
    stdin_open:    true
    tty:           true
    env_file: .env
    build:
      context: ./base_php7_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Log location
      - ./log/base_php7:/srv/app/logs
      # Extra platform Configuration
      - ./base_php7_developer/php.ini:/etc/php7/conf.d/overrides.ini
      # Project files
      - ~/pivot88/Pivot88WebPlatform:/srv
      - ~/pivot88/DataBundle:/srv/managed/DataBundle
      - ~/.ssh:/home/php/.ssh

  app_platform:
    image: symball/pivot88-docker:platform_php7
    env_file: .env
    build:
      context: ./platform_php7_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes_from:
      - app_environment
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      - ./base_php7_developer/php.ini:/etc/php7/conf.d/overrides.ini
      - ./platform_php7_developer/pool_config.conf:/etc/php7/php-fpm.d/www.conf
      - ./log/platform_php7:/var/log/php7

  external_gateway:
    image:         nginx:mainline-alpine
    links:
      - app_platform
      - database_couch
      - database_sql
      - jenkins
    ports:
      - 8080:80
      - 4430:443
      - 3306:3306
      # - 5984:5984
    volumes:
      - ./nginx/dev_config/http:/etc/nginx/conf.d
      - ./nginx/dev_config/stream:/etc/nginx/conf.e
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    volumes_from:
      - app_platform

  database_sql:
    image:         mysql/mysql-server:5.5
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log
    # TODO substitute with key service
    environment:
      - MYSQL_ROOT_PASSWORD=docker_stack
      - MYSQL_DATABASE=docker_stack
      - MYSQL_ROOT_HOST=%

  # Fake SMTP service
  mail_server:
    image: mailhog/mailhog
    ports:
      - 8081:8025

  #
  # JENKINS AUTOMATION
  #
  jenkins:
    image: symball/jenkins-with-docker
    env_file: .env
    build:
      context: ./jenkins
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  # ELK Stack
  #
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
#     volumes:
#       - ./elasticsearch/config:/usr/share/elasticsearch/config
#     # ports:
#     #   - "9200:9200"
#     #   - "9300:9300"
#     environment:
#       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#     networks:
#       - elk
#
#   logstash:
#     image: docker.elastic.co/logstash/logstash:5.6.0
#     volumes:
#       - ./logstash/config:/usr/share/logstash/config
#       - ./logstash/pipeline:/usr/share/logstash/pipeline
#     # ports:
#     #   - "5000:5000"
#     environment:
#       LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch
#
#   kibana:
#     image: docker.elastic.co/kibana/kibana:5.6.0
#     volumes:
#       - ./kibana:/usr/share/kibana/config
#     # ports:
#     #   - "5601:5601"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch
#
# networks:
#
#   elk:
#     driver: bridge
