version:           '2'
services:

  app_environment:
    image: base:php5_developer
    stdin_open:    true
    tty:           true
    env_file: .env
    build:
      context: ./docker/base_php5_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Log location
      - ./docker/log/base_symfony_php7:/srv/app/logs
      # Extra platform Configuration
      - ./docker/base_php7/php.ini:/etc/php7/conf.d/overrides.ini
      # Project files
      - /Users/simon/Development/pivot88/Pivot88WebPlatform:/srv
      # - /Users/simon/Development/temp/Pivot88WebPlatform:/srv
      #
      #  --- REQUIRED CHANGES BELOW ---
      #
      #  - VCS Access
      #  Set the first parameter to a path on your system with an SSH config and
      #  the keys to access the reopositories being used
      - /Users/simon/.ssh:/php/.ssh

  app_platform:
    build:
      context:       ./docker/platform_php7
    image:         platform:php7
    volumes_from:
      - app_environment
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Extra platform Configuration
      - ./docker/platform_php7/pool_config.conf:/etc/php7/php-fpm.d/www.conf
      - ./docker/log/platform_php7:/var/log/php7

  external_gateway:
    image:         nginx:mainline-alpine
    links:
      - app_platform
      - database_couch
      - database_sql
    ports:
      - 8080:80
      - 4430:443
    volumes:
      - ./docker/nginx/core_config:/etc/nginx/conf.d
      # - ./docker/nginx/extra_config/sql.conf:/etc/nginx/conf.d/sql.conf
      - ./docker/log/nginx:/var/log/nginx
    volumes_from:
      - app_platform

  database_sql:
    image:         mysql/mysql-server:5.5
    volumes:
      - /Users/simon/Development/pivot88/docker/data/mysql:/var/lib/mysql
      - ./docker/log/mysql:/var/log
    ports:
      - 3306:3306
    # TODO Move in to a management system
    environment:
      - MYSQL_ROOT_PASSWORD=symfony
      - MYSQL_ROOT_HOST=%

  # Fake SMTP service
  mail_server:
    image: mailhog/mailhog
    ports:
      - 82:8025

  # Log grabber
  # log_elk:
  #    image: sebp/elk:550
  #    ports:
  #     - 81:80
  #    volumes:
  #     - ./docker/elk/logstash:/etc/logstash
  #     - ./docker/elk/logstash/patterns:/opt/logstash/patterns
  #     - ./docker/log:/internal_logs
